ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_v2
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_v2/common
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_v2/sensor/cci
ifdef CONFIG_USE_CAMERA_HW_BIG_DATA
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_v2/sensor
endif
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
